[template]
ignore = [
    ".git",
    ".github/workflows/automerge.yml",
    ".github/workflows/release-please.yml",
    ".github/workflows/test.yml",
    ".github/dependabot.yml",
    "target",
    "CHANGELOG.md",
    "Cargo.lock"
]

[hooks]
post = ["./scripts/post-script.rhai"]

[placeholders.actions]
type = "bool"
prompt = "Use GitHub Actions?"
default = true

[conditional.actions.placeholders.sccache]
type = "bool"
prompt = "Use sccache in GitHub Actions?"
default = true

[placeholders.docker]
type = "bool"
prompt = "Use Docker?"
default = true

[conditional.docker.placeholders.dockerdebian]
type = "bool"
prompt = "Use Debian Dockerfile?"
default = true

[conditional.docker.placeholders.dockeralpine]
type = "bool"
prompt = "Use Alpine Dockerfile?"
default = true

[placeholders.renovate]
type = "bool"
prompt = "Use Renovate instead of Dependabot?"
default = false