ARG PACKAGE=rust-template
ARG TARGET=x86_64-unknown-linux-musl

FROM lukemathwalker/cargo-chef:latest-rust-alpine3.23@sha256:5b2b5c6585c537a2795a477e93ebba85b4a2887e11ee9bddd34ad607e53ccec0 AS chef
WORKDIR /prod

FROM chef as planner
ARG PACKAGE
COPY . .
RUN cargo chef prepare --bin ${PACKAGE} --recipe-path recipe.json

FROM chef as builder
ARG PACKAGE
ARG TARGET
COPY --from=planner /prod/recipe.json recipe.json
RUN cargo chef cook --release --target ${TARGET} --bin ${PACKAGE} --recipe-path recipe.json
COPY . .
RUN cargo build --release --target ${TARGET} --bin ${PACKAGE}

FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40 AS runner
ARG PACKAGE
ARG TARGET
COPY --from=builder /prod/target/${TARGET}/release/${PACKAGE} /bin/my-app
CMD ["/bin/my-app"]